#!/bin/bash
# A seemingly overcomplicated way to reset the partitions of my flash drive appropriately named Beluga..
ID="usb-SanDisk_Ultra_Fit_4C530001020204112000-0:0"
DEV=$(ls -l /dev/disk/by-id | grep "$ID " | cut -s -d "/" -f 3)
CHECK=$(sudo fdisk -l /dev/$DEV)
echo -e "o\nn\np\n1\n\n\nt\n7\nw\n" | sudo fdisk /dev/$DEV
PART=1
sudo mkfs.ntfs -f /dev/$DEV$PART
