#!/bin/bash

for id in $(xinput --list | sed -n '/Logitech MX Master.*pointer/s/.*=\([0-9]\+\).*/\1/p')
do
  xinput --set-prop $id "Device Accel Profile" -1
  xinput --set-prop $id "Device Accel Constant Deceleration"
done
