#!/usr/bin/env ruby
# Script from Brandon to prefix a commit message with first part of the branch name you are on which should be the JIRA card ID
`git rev-parse --abbrev-ref HEAD`.strip =~ /^\S+\/(\w+?\-\w+)\-?.*/
system "commit -m '#{$1} #{ARGV[0]}'"
