#!/bin/bash
# edit log entry for the current day in geeknote
DATE=$(date +%Y.%m.%d)
echo $DATE
if [[ $(geeknote find $DATE) ]]
then
	echo 'Log exists, editing.'
	geeknote edit $DATE
else
	echo "Log doesn't exist, creating one for today."
	geeknote create --notebook Logs --title $DATE
	geeknote edit $DATE
fi
