#!/bin/bash
# adds your public ssh key to the remote server
# $1 = user@server
# $2 = ssh key
if [[ -n "$2" ]]; then
  cat $2 | ssh $1 "cat >> ~/.ssh/authorized_keys"
else
  cat ~/.ssh/id_rsa.pub | ssh $1 "cat >> ~/.ssh/authorized_keys"
fi
